Repository GameDevTecnico/cubos, pull requests merged in 2021-10, with the labels that each got.

#45 Doxygen workflow fixes
  .github/workflows/build-doxygen-docs.yml
Labels: enhancement

#59 Removed CMakeSettings.json & .vscode/settings.json
  .gitignore
  .vscode/settings.json
  CMakeSettings.json
Labels: enhancement

#63 Fixed OpenGL error 1281 on OGLShaderPipeline::getBindingPoint()
  src/gl/ogl_render_device.cpp
Labels: bug

#50 Abstract Window, glfw implementation.
  CMakeLists.txt
  include/cubos/io/glfw_window.hpp
  include/cubos/io/window.hpp
  src/entry.cpp
  src/gl/ogl_render_device.cpp
  src/io/glfw_window.cpp
Labels: enhancement

#38 Added event class
  include/cubos/event.hpp
Labels: 1st priority

#39 Add events to the Window class
  CMakeLists.txt
  include/cubos/event.hpp
  include/cubos/io/keyboard.hpp
  include/cubos/io/window.hpp
  src/cubos/entry.cpp
  src/cubos/gl/ogl_render_device.cpp
  src/cubos/io/glfw_window.cpp
  src/cubos/io/glfw_window.hpp
  src/cubos/io/window.cpp
  src/cubos/log.cpp
  src/cubos/settings.cpp
  src/entry.cpp
  src/io/glfw_window.cpp
Labels: 1st priority

#66 Added periods to the end of documentation comments
  include/cubos/event.hpp
  include/cubos/gl/ogl_render_device.hpp
  include/cubos/gl/render_device.hpp
  include/cubos/io/keyboard.hpp
  include/cubos/io/window.hpp
  include/cubos/log.hpp
  include/cubos/settings.hpp
Labels: documentation
