Repository GameDevTecnico/cubos, pull requests merged in 2023-08, with the labels that each got.

#444 Change docs CI publish dir
  .github/workflows/build-doxygen-docs.yml
Labels: bug, documentation

#442 Add a pull request template with the guidelines
  .github/pull_request_template.md
Labels: documentation

#455 Rename tools
  CMakeLists.txt
  README.md
  cmake/QuadradosGenerate.cmake
  core/include/cubos/core/data/fs/embedded_archive.hpp
  core/samples/data/fs/embedded_archive/embed.cpp
  core/samples/data/fs/embedded_archive/main.cpp
  core/tests/CMakeLists.txt
  core/tests/data/fs/embedded_archive.cpp
  docs/pages/1_structure/3_cubinhos.md
  docs/pages/1_structure/main.md
  engine/CMakeLists.txt
  engine/samples/CMakeLists.txt
  tools/CMakeLists.txt
  tools/cubinhos/CMakeLists.txt
  tools/quadrados/CMakeLists.txt
  tools/quadrados/src/convert.cpp
  tools/quadrados/src/embed.cpp
  tools/quadrados/src/entry.cpp
  tools/quadrados/src/generate.cpp
  tools/quadrados/src/tools.hpp
  tools/tesserato/CMakeLists.txt
  tools/tesseratos/CMakeLists.txt
  tools/tesseratos/assets/example_asset.txt
  tools/tesseratos/assets/example_asset.txt.meta
  tools/tesseratos/assets/subfolder/example_asset_2.txt
  tools/tesseratos/assets/subfolder/example_asset_2.txt.meta
  tools/tesseratos/assets/subfolder/subsubFolder/example_asset_3.txt
  tools/tesseratos/assets/subfolder/subsubFolder/example_asset_3.txt.meta
  tools/tesseratos/src/main.cpp
Labels: tools
