Repository GameDevTecnico/cubos, pull requests merged in 2023-11, with the labels that each got.

#784 fix(ci): bump clang-tidy to 17
  .github/workflows/clang-tidy-lint.yml
Labels: C-Crash, A-Meta, B-CI

#786 fix(ci): actually use clang-tidy 17
  .github/workflows/clang-tidy-lint.yml
Labels: C-Crash, A-Meta, B-CI

#787 Fix clang-tidy warnings on generated file
  .github/workflows/clang-tidy-lint.yml
Labels: C-Compile-Error, A-Meta, B-CI

#794 fix(ci): revert to clang-tidy 14
  .github/workflows/clang-tidy-lint.yml
Labels: C-Crash, A-Meta, B-CI

#789 Include tesseratos in clang tidy action
  .github/workflows/clang-tidy-lint.yml
Labels: A-Meta, B-CI

#798 docs(tesseratos): fix entity name format in scenes
  tools/tesseratos/samples/main/assets/main.cubos
  tools/tesseratos/samples/main/assets/sub.cubos
Labels: A-Tesseratos, C-Crash, C-Documentation

#807 Automatically copy issue labels to linked PRs
  .github/workflows/copy-labels.yml
Labels: D-Good-First-Issue, P-Backlog, B-CI

#820 Add conventional commits action
  .github/workflows/conventional-commits.yml
Labels: A-Meta, B-CI

#805 Add a popup for selecting an asset of a given type
  tools/tesseratos/CMakeLists.txt
  tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
  tools/tesseratos/src/tesseratos/asset_explorer/popup.cpp
Labels: A-Engine, B-Assets, B-Tools

#828 fix(tesseratos): rename components to fit current scheme
  tools/tesseratos/samples/main/assets/main.cubos
  tools/tesseratos/samples/main/assets/sub.cubos
Labels: A-Tesseratos, C-Crash, S-Triage

#847 Allow registering components whose type is unknown at compile time
  core/include/cubos/core/ecs/world.hpp
  core/src/cubos/core/ecs/world.cpp
Labels: A-Core, B-ECS
